package alku.csrp.client.model;

import alku.csrp.Csrp;
import com.github.alexthe666.citadel.client.model.AdvancedModelBox;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import net.minecraft.client.Minecraft;
import net.minecraft.resources.ResourceLocation;

/**
 * Evaluates the animation formulae exported from the 1.10.8 Tabula Java models.
 * The JSON is a lossless intermediate generated by the project's extractor;
 * all evaluated transforms are written directly to Citadel model boxes.
 */
final class LegacyAnimationLibrary {
    private static final float DEG_TO_RAD = (float) (Math.PI / 180.0D);

    private final String modelId;
    private final Map<String, AnimationClip> clips = new LinkedHashMap<>();

    LegacyAnimationLibrary(String modelId) {
        this.modelId = modelId;
        load();
    }

    float duration(String animationName) {
        AnimationClip clip = findClip(animationName);
        return clip == null ? 0.0F : clip.length();
    }

    boolean contains(String animationName) {
        return findClip(animationName) != null;
    }

    void apply(LegacyTabulaModel<?> model, String animationName, float animationTime,
            float rotationScale) {
        AnimationClip clip = findClip(animationName);
        if (clip == null) {
            return;
        }
        float time = clip.loop() && clip.length() > 0.0F
                ? Math.floorMod((long) (animationTime * 1_000_000.0F),
                        Math.max(1L, (long) (clip.length() * 1_000_000.0F))) / 1_000_000.0F
                : Math.min(animationTime, clip.length());
        for (BoneAnimation bone : clip.bones()) {
            AdvancedModelBox part = model.findPart(bone.name());
            if (part == null) {
                continue;
            }
            if (bone.rotation() != null) {
                Vec3 value = bone.rotation().sample(time);
                part.rotateAngleX += -value.x() * DEG_TO_RAD * rotationScale;
                part.rotateAngleY += value.y() * DEG_TO_RAD * rotationScale;
                part.rotateAngleZ += -value.z() * DEG_TO_RAD * rotationScale;
            }
            if (bone.position() != null) {
                Vec3 value = bone.position().sample(time);
                part.rotationPointX += -value.x();
                part.rotationPointY += -value.y();
                part.rotationPointZ += -value.z();
            }
        }
    }

    private AnimationClip findClip(String animationName) {
        AnimationClip exact = clips.get(animationName);
        if (exact != null) {
            return exact;
        }
        int separator = animationName.lastIndexOf('.');
        return separator < 0 ? null : clips.get(animationName.substring(separator + 1));
    }

    private void load() {
        ResourceLocation location = ResourceLocation.fromNamespaceAndPath(
                Csrp.MODID, "animations/" + modelId + ".animation.json");
        try (InputStream stream = Minecraft.getInstance().getResourceManager()
                .getResource(location)
                .orElseThrow(() -> new IOException("Missing legacy Tabula animation " + location))
                .open();
                InputStreamReader reader = new InputStreamReader(stream, StandardCharsets.UTF_8)) {
            JsonObject animations = JsonParser.parseReader(reader).getAsJsonObject()
                    .getAsJsonObject("animations");
            for (Map.Entry<String, JsonElement> entry : animations.entrySet()) {
                clips.put(entry.getKey(), parseClip(entry.getValue().getAsJsonObject()));
            }
        } catch (IOException | RuntimeException exception) {
            throw new IllegalStateException("Unable to load legacy Tabula animations " + modelId, exception);
        }
    }

    private static AnimationClip parseClip(JsonObject json) {
        boolean loop = json.has("loop") && json.get("loop").getAsBoolean();
        float length = json.has("animation_length") ? json.get("animation_length").getAsFloat() : 0.0F;
        List<BoneAnimation> bones = new ArrayList<>();
        JsonObject boneObject = json.has("bones") ? json.getAsJsonObject("bones") : new JsonObject();
        for (Map.Entry<String, JsonElement> entry : boneObject.entrySet()) {
            JsonObject bone = entry.getValue().getAsJsonObject();
            VectorChannel rotation = bone.has("rotation") ? parseChannel(bone.get("rotation")) : null;
            VectorChannel position = bone.has("position") ? parseChannel(bone.get("position")) : null;
            bones.add(new BoneAnimation(entry.getKey(), rotation, position));
        }
        return new AnimationClip(loop, length, List.copyOf(bones));
    }

    private static VectorChannel parseChannel(JsonElement element) {
        if (element.isJsonArray()) {
            return new ConstantChannel(parseVector(element.getAsJsonArray()));
        }
        JsonObject object = element.getAsJsonObject();
        List<Keyframe> frames = new ArrayList<>();
        for (Map.Entry<String, JsonElement> entry : object.entrySet()) {
            float time = Float.parseFloat(entry.getKey());
            JsonElement value = entry.getValue();
            if (value.isJsonArray()) {
                ExpressionVector vector = parseVector(value.getAsJsonArray());
                frames.add(new Keyframe(time, vector, vector, Interpolation.LINEAR));
                continue;
            }
            JsonObject frame = value.getAsJsonObject();
            ExpressionVector pre = frame.has("pre")
                    ? parseVector(frame.getAsJsonArray("pre")) : null;
            ExpressionVector post = frame.has("post")
                    ? parseVector(frame.getAsJsonArray("post")) : null;
            if (pre == null) {
                pre = post;
            }
            if (post == null) {
                post = pre;
            }
            String mode = frame.has("lerp_mode") ? frame.get("lerp_mode").getAsString() : "linear";
            frames.add(new Keyframe(time, pre, post,
                    "catmullrom".equals(mode) ? Interpolation.CATMULL_ROM : Interpolation.LINEAR));
        }
        frames.sort(Comparator.comparingDouble(Keyframe::time));
        return new KeyframedChannel(List.copyOf(frames));
    }

    private static ExpressionVector parseVector(JsonArray array) {
        return new ExpressionVector(expression(array.get(0)),
                expression(array.get(1)), expression(array.get(2)));
    }

    private static Expression expression(JsonElement element) {
        if (element.isJsonPrimitive() && element.getAsJsonPrimitive().isNumber()) {
            double value = element.getAsDouble();
            return ignored -> value;
        }
        return new MolangExpression(element.getAsString());
    }

    private interface VectorChannel {
        Vec3 sample(float time);
    }

    private record ConstantChannel(ExpressionVector value) implements VectorChannel {
        @Override
        public Vec3 sample(float time) {
            return value.evaluate(time);
        }
    }

    private record KeyframedChannel(List<Keyframe> frames) implements VectorChannel {
        @Override
        public Vec3 sample(float time) {
            if (frames.isEmpty()) {
                return Vec3.ZERO;
            }
            if (time <= frames.getFirst().time()) {
                return frames.getFirst().pre().evaluate(time);
            }
            if (time >= frames.getLast().time()) {
                return frames.getLast().post().evaluate(time);
            }
            int upper = 1;
            while (upper < frames.size() && frames.get(upper).time() < time) {
                upper++;
            }
            Keyframe left = frames.get(upper - 1);
            Keyframe right = frames.get(upper);
            float progress = (time - left.time()) / Math.max(1.0E-6F, right.time() - left.time());
            Vec3 p1 = left.post().evaluate(time);
            Vec3 p2 = right.pre().evaluate(time);
            if (left.interpolation() != Interpolation.CATMULL_ROM) {
                return p1.lerp(p2, progress);
            }
            Vec3 p0 = upper >= 2 ? frames.get(upper - 2).post().evaluate(time) : p1;
            Vec3 p3 = upper + 1 < frames.size()
                    ? frames.get(upper + 1).pre().evaluate(time) : p2;
            return Vec3.catmullRom(p0, p1, p2, p3, progress);
        }
    }

    private record AnimationClip(boolean loop, float length, List<BoneAnimation> bones) {
    }

    private record BoneAnimation(String name, VectorChannel rotation, VectorChannel position) {
    }

    private record Keyframe(float time, ExpressionVector pre, ExpressionVector post,
            Interpolation interpolation) {
    }

    private enum Interpolation {
        LINEAR,
        CATMULL_ROM
    }

    private record ExpressionVector(Expression x, Expression y, Expression z) {
        Vec3 evaluate(float time) {
            return new Vec3((float) x.evaluate(time), (float) y.evaluate(time),
                    (float) z.evaluate(time));
        }
    }

    private record Vec3(float x, float y, float z) {
        private static final Vec3 ZERO = new Vec3(0.0F, 0.0F, 0.0F);

        Vec3 lerp(Vec3 other, float progress) {
            return new Vec3(x + (other.x - x) * progress,
                    y + (other.y - y) * progress,
                    z + (other.z - z) * progress);
        }

        static Vec3 catmullRom(Vec3 p0, Vec3 p1, Vec3 p2, Vec3 p3, float t) {
            float t2 = t * t;
            float t3 = t2 * t;
            return new Vec3(catmull(p0.x, p1.x, p2.x, p3.x, t, t2, t3),
                    catmull(p0.y, p1.y, p2.y, p3.y, t, t2, t3),
                    catmull(p0.z, p1.z, p2.z, p3.z, t, t2, t3));
        }

        private static float catmull(float p0, float p1, float p2, float p3,
                float t, float t2, float t3) {
            return 0.5F * (2.0F * p1 + (-p0 + p2) * t
                    + (2.0F * p0 - 5.0F * p1 + 4.0F * p2 - p3) * t2
                    + (-p0 + 3.0F * p1 - 3.0F * p2 + p3) * t3);
        }
    }

    @FunctionalInterface
    private interface Expression {
        double evaluate(double animationTime);
    }

    /** Minimal MoLang evaluator covering every expression emitted by the extractor. */
    private static final class MolangExpression implements Expression {
        private final Node root;

        private MolangExpression(String source) {
            Parser parser = new Parser(source);
            root = parser.parse();
        }

        @Override
        public double evaluate(double animationTime) {
            return root.evaluate(animationTime);
        }
    }

    @FunctionalInterface
    private interface Node {
        double evaluate(double animationTime);
    }

    private static final class Parser {
        private final String source;
        private int cursor;

        private Parser(String source) {
            this.source = source;
        }

        Node parse() {
            Node result = ternary();
            whitespace();
            if (cursor != source.length()) {
                throw error("Unexpected token");
            }
            return result;
        }

        private Node ternary() {
            Node condition = comparison();
            whitespace();
            if (!take('?')) {
                return condition;
            }
            Node ifTrue = ternary();
            require(':');
            Node ifFalse = ternary();
            return time -> condition.evaluate(time) != 0.0D
                    ? ifTrue.evaluate(time) : ifFalse.evaluate(time);
        }

        private Node comparison() {
            Node left = addition();
            while (true) {
                String operator = operator(">=", "<=", "==", "!=", ">", "<");
                if (operator == null) {
                    return left;
                }
                Node previous = left;
                Node right = addition();
                left = time -> compare(operator, previous.evaluate(time), right.evaluate(time));
            }
        }

        private Node addition() {
            Node left = multiplication();
            while (true) {
                whitespace();
                if (take('+')) {
                    Node previous = left;
                    Node right = multiplication();
                    left = time -> previous.evaluate(time) + right.evaluate(time);
                } else if (take('-')) {
                    Node previous = left;
                    Node right = multiplication();
                    left = time -> previous.evaluate(time) - right.evaluate(time);
                } else {
                    return left;
                }
            }
        }

        private Node multiplication() {
            Node left = unary();
            while (true) {
                whitespace();
                if (take('*')) {
                    Node previous = left;
                    Node right = unary();
                    left = time -> previous.evaluate(time) * right.evaluate(time);
                } else if (take('/')) {
                    Node previous = left;
                    Node right = unary();
                    left = time -> previous.evaluate(time) / right.evaluate(time);
                } else {
                    return left;
                }
            }
        }

        private Node unary() {
            whitespace();
            if (take('+')) {
                return unary();
            }
            if (take('-')) {
                Node value = unary();
                return time -> -value.evaluate(time);
            }
            if (take('!')) {
                Node value = unary();
                return time -> value.evaluate(time) == 0.0D ? 1.0D : 0.0D;
            }
            return primary();
        }

        private Node primary() {
            whitespace();
            if (take('(')) {
                Node value = ternary();
                require(')');
                return value;
            }
            if (cursor < source.length()
                    && (Character.isDigit(source.charAt(cursor)) || source.charAt(cursor) == '.')) {
                double number = number();
                return ignored -> number;
            }
            String identifier = identifier();
            if (identifier.equals("query.anim_time")) {
                return time -> time;
            }
            if (identifier.equals("true")) {
                return ignored -> 1.0D;
            }
            if (identifier.equals("false")) {
                return ignored -> 0.0D;
            }
            whitespace();
            if (!take('(')) {
                throw error("Unknown identifier " + identifier);
            }
            List<Node> arguments = new ArrayList<>();
            whitespace();
            if (!take(')')) {
                do {
                    arguments.add(ternary());
                    whitespace();
                } while (take(','));
                require(')');
            }
            return function(identifier, arguments);
        }

        private Node function(String name, List<Node> arguments) {
            return switch (name) {
                case "math.cos" -> unaryFunction(name, arguments,
                        value -> Math.cos(Math.toRadians(value)));
                case "math.sin" -> unaryFunction(name, arguments,
                        value -> Math.sin(Math.toRadians(value)));
                case "math.min" -> binaryFunction(name, arguments, Math::min);
                case "math.max" -> binaryFunction(name, arguments, Math::max);
                default -> throw error("Unknown function " + name);
            };
        }

        private Node unaryFunction(String name, List<Node> arguments,
                java.util.function.DoubleUnaryOperator operator) {
            if (arguments.size() != 1) {
                throw error(name + " expects one argument");
            }
            return time -> operator.applyAsDouble(arguments.getFirst().evaluate(time));
        }

        private Node binaryFunction(String name, List<Node> arguments,
                java.util.function.DoubleBinaryOperator operator) {
            if (arguments.size() != 2) {
                throw error(name + " expects two arguments");
            }
            return time -> operator.applyAsDouble(arguments.get(0).evaluate(time),
                    arguments.get(1).evaluate(time));
        }

        private String operator(String... candidates) {
            whitespace();
            for (String candidate : candidates) {
                if (source.startsWith(candidate, cursor)) {
                    cursor += candidate.length();
                    return candidate;
                }
            }
            return null;
        }

        private double number() {
            int start = cursor;
            while (cursor < source.length()) {
                char current = source.charAt(cursor);
                if (!Character.isDigit(current) && current != '.' && current != 'e'
                        && current != 'E' && current != '+' && current != '-') {
                    break;
                }
                if ((current == '+' || current == '-') && cursor > start
                        && source.charAt(cursor - 1) != 'e' && source.charAt(cursor - 1) != 'E') {
                    break;
                }
                cursor++;
            }
            return Double.parseDouble(source.substring(start, cursor));
        }

        private String identifier() {
            whitespace();
            int start = cursor;
            while (cursor < source.length()) {
                char current = source.charAt(cursor);
                if (!Character.isLetterOrDigit(current) && current != '_' && current != '.') {
                    break;
                }
                cursor++;
            }
            if (start == cursor) {
                throw error("Expected value");
            }
            return source.substring(start, cursor);
        }

        private void whitespace() {
            while (cursor < source.length() && Character.isWhitespace(source.charAt(cursor))) {
                cursor++;
            }
        }

        private boolean take(char expected) {
            whitespace();
            if (cursor < source.length() && source.charAt(cursor) == expected) {
                cursor++;
                return true;
            }
            return false;
        }

        private void require(char expected) {
            if (!take(expected)) {
                throw error("Expected '" + expected + "'");
            }
        }

        private IllegalArgumentException error(String message) {
            return new IllegalArgumentException(message + " at " + cursor + " in " + source);
        }

        private static double compare(String operator, double left, double right) {
            return switch (operator) {
                case ">=" -> left >= right ? 1.0D : 0.0D;
                case "<=" -> left <= right ? 1.0D : 0.0D;
                case "==" -> left == right ? 1.0D : 0.0D;
                case "!=" -> left != right ? 1.0D : 0.0D;
                case ">" -> left > right ? 1.0D : 0.0D;
                case "<" -> left < right ? 1.0D : 0.0D;
                default -> 0.0D;
            };
        }
    }
}
