package alku.csrp.client.model.tabula.inborn;

import alku.csrp.client.model.tabula.ModelSRP;
import alku.csrp.entity.RupterEntity;
import com.github.alexthe666.citadel.client.model.AdvancedModelBox;
import net.minecraft.util.Mth;

/** Direct Citadel port of SRParasites 1.10.8's Tabula-exported {@code ModelMudo}. */
public final class ModelMudo extends ModelSRP<RupterEntity> {
   public AdvancedModelBox mainbody;
   public AdvancedModelBox joingRB;
   public AdvancedModelBox jointLB;
   public AdvancedModelBox jointFLLX;
   public AdvancedModelBox jointFRLX;
   public AdvancedModelBox jointBLLX;
   public AdvancedModelBox jointBRLX;
   public AdvancedModelBox head;
   public AdvancedModelBox body;
   public AdvancedModelBox body_1;
   public AdvancedModelBox body_2;
   public AdvancedModelBox body_3;
   public AdvancedModelBox body_4;
   public AdvancedModelBox JD;
   public AdvancedModelBox jointFLLY;
   public AdvancedModelBox leg;
   public AdvancedModelBox jointFLL1;
   public AdvancedModelBox leg_1;
   public AdvancedModelBox jointFLL2;
   public AdvancedModelBox leg_2;
   public AdvancedModelBox JD_1;
   public AdvancedModelBox jointFRLY;
   public AdvancedModelBox leg_3;
   public AdvancedModelBox jointFRL1;
   public AdvancedModelBox leg_4;
   public AdvancedModelBox jointFRL2;
   public AdvancedModelBox leg_5;
   public AdvancedModelBox JD_2;
   public AdvancedModelBox jointBLLY;
   public AdvancedModelBox leg_6;
   public AdvancedModelBox jointBLL1;
   public AdvancedModelBox leg_7;
   public AdvancedModelBox jointBLL2;
   public AdvancedModelBox leg_8;
   public AdvancedModelBox JD_3;
   public AdvancedModelBox jointBRLY;
   public AdvancedModelBox leg_9;
   public AdvancedModelBox jointBRL1;
   public AdvancedModelBox leg_10;
   public AdvancedModelBox jointBRL2;
   public AdvancedModelBox leg_11;
   public AdvancedModelBox hair_jointRTL;
   public AdvancedModelBox hair_jointRTR;
   public AdvancedModelBox hair_jointRTM;
   public AdvancedModelBox hair_jointRTLL;
   public AdvancedModelBox hair_jointRTRR;
   public AdvancedModelBox hair;
   public AdvancedModelBox hair_jointL1;
   public AdvancedModelBox hair_1;
   public AdvancedModelBox hair_jointL2;
   public AdvancedModelBox hair_2;
   public AdvancedModelBox hair_jointL3;
   public AdvancedModelBox hair_3;
   public AdvancedModelBox hair_jointL4;
   public AdvancedModelBox hair_4;
   public AdvancedModelBox hair_jointL5;
   public AdvancedModelBox hair_5;
   public AdvancedModelBox hair_jointL6;
   public AdvancedModelBox hair_6;
   public AdvancedModelBox hair_7;
   public AdvancedModelBox hair_jointR1;
   public AdvancedModelBox hair_8;
   public AdvancedModelBox hair_jointR2;
   public AdvancedModelBox hair_9;
   public AdvancedModelBox hair_jointR3;
   public AdvancedModelBox hair_10;
   public AdvancedModelBox hair_jointR4;
   public AdvancedModelBox hair_11;
   public AdvancedModelBox hair_jointR5;
   public AdvancedModelBox hair_12;
   public AdvancedModelBox hair_jointR6;
   public AdvancedModelBox hair_13;
   public AdvancedModelBox hair_14;
   public AdvancedModelBox hair_jointM1;
   public AdvancedModelBox hair_15;
   public AdvancedModelBox hair_jointM2;
   public AdvancedModelBox hair_16;
   public AdvancedModelBox hair_jointM3;
   public AdvancedModelBox hair_17;
   public AdvancedModelBox hair_jointM4;
   public AdvancedModelBox hair_18;
   public AdvancedModelBox hair_jointM5;
   public AdvancedModelBox hair_19;
   public AdvancedModelBox hair_jointM6;
   public AdvancedModelBox hair_20;
   public AdvancedModelBox hair_21;
   public AdvancedModelBox hair_jointLL1;
   public AdvancedModelBox hair_22;
   public AdvancedModelBox hair_jointLL2;
   public AdvancedModelBox hair_23;
   public AdvancedModelBox hair_jointLL3;
   public AdvancedModelBox hair_24;
   public AdvancedModelBox hair_jointLL4;
   public AdvancedModelBox hair_25;
   public AdvancedModelBox hair_jointLL5;
   public AdvancedModelBox hair_26;
   public AdvancedModelBox hair_jointLL6;
   public AdvancedModelBox hair_27;
   public AdvancedModelBox hair_28;
   public AdvancedModelBox hair_jointRR1;
   public AdvancedModelBox hair_29;
   public AdvancedModelBox hair_jointRR2;
   public AdvancedModelBox hair_30;
   public AdvancedModelBox hair_jointRR3;
   public AdvancedModelBox hair_31;
   public AdvancedModelBox hair_jointRR4;
   public AdvancedModelBox hair_32;
   public AdvancedModelBox hair_jointRR5;
   public AdvancedModelBox hair_33;
   public AdvancedModelBox hair_jointRR6;
   public AdvancedModelBox hair_34;
   public AdvancedModelBox tail;
   public AdvancedModelBox tail_1;

   public ModelMudo() {
      this.texWidth = 64;
      this.texHeight = 50;
      this.hair_jointRR2 = new AdvancedModelBox(this, 23, 36);
      this.hair_jointRR2.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointRR2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointRTRR = new AdvancedModelBox(this, 16, 21);
      this.hair_jointRTRR.setRotationPoint(-3.5F, -3.0F, -1.4F);
      this.hair_jointRTRR.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.JD_3 = new AdvancedModelBox(this, 58, 14);
      this.JD_3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.JD_3.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.JD_3, 0.0F, (float) (-Math.PI * 3.0 / 4.0), 0.0F);
      this.hair_13 = new AdvancedModelBox(this, 29, 28);
      this.hair_13.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_13.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_13, 0.61086524F, 0.0F, 0.0F);
      this.hair_26 = new AdvancedModelBox(this, 0, 35);
      this.hair_26.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_26.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_26, 0.61086524F, 0.0F, 0.0F);
      this.hair_24 = new AdvancedModelBox(this, 39, 33);
      this.hair_24.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_24.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_24, -0.61086524F, 0.0F, 0.0F);
      this.hair_22 = new AdvancedModelBox(this, 54, 32);
      this.hair_22.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_22.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_22, -0.82030475F, 0.0F, 0.0F);
      this.hair_12 = new AdvancedModelBox(this, 21, 28);
      this.hair_12.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_12.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_12, 0.61086524F, 0.0F, 0.0F);
      this.hair_jointL4 = new AdvancedModelBox(this, 58, 23);
      this.hair_jointL4.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointL4.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.tail_1 = new AdvancedModelBox(this, 16, 40);
      this.tail_1.setRotationPoint(0.0F, -0.1F, 2.6F);
      this.tail_1.addBox(-1.5F, -1.0F, 0.0F, 3, 2, 5, 0.0F);
      this.setRotateAngle(this.tail_1, -0.2268928F, 0.0F, 0.0F);
      this.leg_10 = new AdvancedModelBox(this, 58, 16);
      this.leg_10.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg_10.addBox(-0.5F, -0.5F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.leg_10, 0.0F, 0.0F, -1.4486233F);
      this.hair_30 = new AdvancedModelBox(this, 26, 36);
      this.hair_30.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_30.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_30, -0.61086524F, 0.0F, 0.0F);
      this.hair = new AdvancedModelBox(this, 17, 21);
      this.hair.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.hair.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair, -2.7576203F, -0.57595867F, 0.0F);
      this.body = new AdvancedModelBox(this, 0, 11);
      this.body.setRotationPoint(0.0F, -3.0F, -4.0F);
      this.body.addBox(-3.0F, -1.5F, -1.0F, 6, 5, 5, 0.0F);
      this.setRotateAngle(this.body, (float) (Math.PI / 9), 0.0F, 0.0F);
      this.hair_jointRR3 = new AdvancedModelBox(this, 52, 36);
      this.hair_jointRR3.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointRR3.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.mainbody = new AdvancedModelBox(this, 0, 0);
      this.mainbody.setRotationPoint(0.0F, 12.9F, 5.7F);
      this.mainbody.addBox(-2.0F, -2.0F, -5.0F, 1, 1, 1, 0.0F);
      this.hair_31 = new AdvancedModelBox(this, 53, 36);
      this.hair_31.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_31.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_31, -0.61086524F, 0.0F, 0.0F);
      this.hair_jointL5 = new AdvancedModelBox(this, 27, 24);
      this.hair_jointL5.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointL5.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.jointBRLY = new AdvancedModelBox(this, 22, 16);
      this.jointBRLY.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.jointBRLY.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointM1 = new AdvancedModelBox(this, 42, 29);
      this.hair_jointM1.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointM1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_29 = new AdvancedModelBox(this, 18, 36);
      this.hair_29.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_29.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_29, -0.82030475F, 0.0F, 0.0F);
      this.hair_jointL6 = new AdvancedModelBox(this, 35, 24);
      this.hair_jointL6.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointL6.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_32 = new AdvancedModelBox(this, 13, 37);
      this.hair_32.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_32.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_32, -0.43633232F, 0.0F, 0.0F);
      this.joingRB = new AdvancedModelBox(this, 4, 0);
      this.joingRB.setRotationPoint(-3.5F, 0.5F, -6.0F);
      this.joingRB.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointR6 = new AdvancedModelBox(this, 26, 28);
      this.hair_jointR6.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointR6.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_20 = new AdvancedModelBox(this, 18, 32);
      this.hair_20.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_20.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_20, 0.61086524F, 0.0F, 0.0F);
      this.hair_jointR4 = new AdvancedModelBox(this, 5, 27);
      this.hair_jointR4.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointR4.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.leg_4 = new AdvancedModelBox(this, 16, 6);
      this.leg_4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg_4.addBox(-0.5F, -0.5F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.leg_4, 0.0F, 0.0F, -1.4486233F);
      this.hair_jointM6 = new AdvancedModelBox(this, 53, 31);
      this.hair_jointM6.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointM6.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.JD = new AdvancedModelBox(this, 44, 0);
      this.JD.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.JD.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.JD, 0.0F, 0.38397244F, 0.0F);
      this.hair_15 = new AdvancedModelBox(this, 43, 29);
      this.hair_15.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_15.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_15, -0.82030475F, 0.0F, 0.0F);
      this.jointFLLX = new AdvancedModelBox(this, 12, 0);
      this.jointFLLX.setRotationPoint(1.7F, 3.0F, -9.5F);
      this.jointFLLX.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.jointBLLY = new AdvancedModelBox(this, 4, 8);
      this.jointBLLY.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.jointBLLY.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.jointBLL1 = new AdvancedModelBox(this, 12, 8);
      this.jointBLL1.setRotationPoint(0.0F, 3.0F, 0.0F);
      this.jointBLL1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.leg_3 = new AdvancedModelBox(this, 8, 6);
      this.leg_3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg_3.addBox(-0.5F, 0.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.leg_3, 0.0F, 0.0F, -0.43633232F);
      this.hair_jointM5 = new AdvancedModelBox(this, 5, 31);
      this.hair_jointM5.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointM5.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_16 = new AdvancedModelBox(this, 34, 30);
      this.hair_16.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_16.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_16, -0.61086524F, 0.0F, 0.0F);
      this.hair_jointM4 = new AdvancedModelBox(this, 59, 30);
      this.hair_jointM4.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointM4.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.jointBRLX = new AdvancedModelBox(this, 24, 0);
      this.jointBRLX.setRotationPoint(-1.7F, 3.8F, -4.7F);
      this.jointBRLX.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.jointFLL2 = new AdvancedModelBox(this, 44, 2);
      this.jointFLL2.setRotationPoint(0.0F, 2.7F, 0.0F);
      this.jointFLL2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointRR4 = new AdvancedModelBox(this, 58, 36);
      this.hair_jointRR4.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointRR4.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointLL1 = new AdvancedModelBox(this, 23, 32);
      this.hair_jointLL1.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointLL1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointLL6 = new AdvancedModelBox(this, 5, 35);
      this.hair_jointLL6.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointLL6.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointL3 = new AdvancedModelBox(this, 13, 23);
      this.hair_jointL3.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointL3.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointRTM = new AdvancedModelBox(this, 8, 21);
      this.hair_jointRTM.setRotationPoint(0.0F, 3.5F, -3.4F);
      this.hair_jointRTM.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointRR5 = new AdvancedModelBox(this, 39, 37);
      this.hair_jointRR5.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointRR5.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.leg_9 = new AdvancedModelBox(this, 36, 16);
      this.leg_9.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg_9.addBox(-0.5F, 0.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.leg_9, 0.0F, 0.0F, -0.38397244F);
      this.hair_2 = new AdvancedModelBox(this, 8, 23);
      this.hair_2.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_2, -0.61086524F, 0.0F, 0.0F);
      this.body_2 = new AdvancedModelBox(this, 0, 2);
      this.body_2.setRotationPoint(-3.0F, 0.0F, 0.0F);
      this.body_2.addBox(-3.5F, -1.0F, -1.0F, 4, 2, 2, 0.0F);
      this.setRotateAngle(this.body_2, 0.0F, 0.0F, -0.38397244F);
      this.JD_1 = new AdvancedModelBox(this, 58, 2);
      this.JD_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.JD_1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.JD_1, 0.0F, 2.7576203F, 0.0F);
      this.hair_33 = new AdvancedModelBox(this, 31, 38);
      this.hair_33.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_33.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_33, 0.61086524F, 0.0F, 0.0F);
      this.hair_23 = new AdvancedModelBox(this, 13, 33);
      this.hair_23.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_23.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_23, -0.61086524F, 0.0F, 0.0F);
      this.jointFLL1 = new AdvancedModelBox(this, 10, 2);
      this.jointFLL1.setRotationPoint(0.0F, 3.0F, 0.0F);
      this.jointFLL1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.jointBLL2 = new AdvancedModelBox(this, 58, 12);
      this.jointBLL2.setRotationPoint(0.0F, 3.7F, 0.0F);
      this.jointBLL2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.body_4 = new AdvancedModelBox(this, 12, 2);
      this.body_4.setRotationPoint(3.0F, 0.0F, 0.0F);
      this.body_4.addBox(-0.5F, -1.0F, -1.0F, 4, 2, 2, 0.0F);
      this.setRotateAngle(this.body_4, 0.0F, 0.0F, 0.38397244F);
      this.hair_jointRR1 = new AdvancedModelBox(this, 49, 35);
      this.hair_jointRR1.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointRR1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointLL3 = new AdvancedModelBox(this, 31, 33);
      this.hair_jointLL3.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointLL3.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_10 = new AdvancedModelBox(this, 8, 27);
      this.hair_10.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_10.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_10, -0.61086524F, 0.0F, 0.0F);
      this.hair_11 = new AdvancedModelBox(this, 48, 27);
      this.hair_11.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_11.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_11, -0.43633232F, 0.0F, 0.0F);
      this.leg_11 = new AdvancedModelBox(this, 52, 18);
      this.leg_11.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg_11.addBox(-0.5F, -1.5F, -1.0F, 1, 7, 2, 0.0F);
      this.setRotateAngle(this.leg_11, 0.0F, 0.0F, 1.7976891F);
      this.hair_4 = new AdvancedModelBox(this, 30, 24);
      this.hair_4.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_4.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_4, -0.43633232F, 0.0F, 0.0F);
      this.hair_jointRTLL = new AdvancedModelBox(this, 12, 21);
      this.hair_jointRTLL.setRotationPoint(3.5F, -3.0F, -1.4F);
      this.hair_jointRTLL.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_9 = new AdvancedModelBox(this, 0, 27);
      this.hair_9.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_9.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_9, -0.61086524F, 0.0F, 0.0F);
      this.hair_6 = new AdvancedModelBox(this, 43, 25);
      this.hair_6.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_6.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_6, 0.61086524F, 0.0F, 0.0F);
      this.jointBRL1 = new AdvancedModelBox(this, 44, 16);
      this.jointBRL1.setRotationPoint(0.0F, 3.0F, 0.0F);
      this.jointBRL1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.body_3 = new AdvancedModelBox(this, 22, 16);
      this.body_3.setRotationPoint(1.0F, 0.0F, 1.0F);
      this.body_3.addBox(-2.0F, -2.0F, -2.0F, 5, 4, 4, 0.0F);
      this.setRotateAngle(this.body_3, 0.0F, -0.43633232F, 0.27925268F);
      this.hair_18 = new AdvancedModelBox(this, 8, 31);
      this.hair_18.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_18.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_18, -0.43633232F, 0.0F, 0.0F);
      this.hair_jointLL4 = new AdvancedModelBox(this, 44, 33);
      this.hair_jointLL4.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointLL4.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.body_1 = new AdvancedModelBox(this, 44, 0);
      this.body_1.setRotationPoint(-1.0F, 0.0F, 1.0F);
      this.body_1.addBox(-3.0F, -2.0F, -2.0F, 5, 4, 4, 0.0F);
      this.setRotateAngle(this.body_1, 0.0F, 0.43633232F, -0.27925268F);
      this.hair_jointM3 = new AdvancedModelBox(this, 39, 30);
      this.hair_jointM3.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointM3.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_21 = new AdvancedModelBox(this, 26, 32);
      this.hair_21.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.hair_21.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_21, -2.3212879F, -1.0821041F, 0.0F);
      this.hair_jointRR6 = new AdvancedModelBox(this, 36, 38);
      this.hair_jointRR6.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointRR6.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.jointBRL2 = new AdvancedModelBox(this, 22, 18);
      this.jointBRL2.setRotationPoint(0.0F, 3.7F, 0.0F);
      this.jointBRL2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.jointFRLY = new AdvancedModelBox(this, 4, 6);
      this.jointFRLY.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.jointFRLY.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointM2 = new AdvancedModelBox(this, 56, 29);
      this.hair_jointM2.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointM2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_17 = new AdvancedModelBox(this, 0, 31);
      this.hair_17.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_17.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_17, -0.61086524F, 0.0F, 0.0F);
      this.leg_1 = new AdvancedModelBox(this, 0, 6);
      this.leg_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg_1.addBox(-0.5F, -0.5F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.leg_1, 0.0F, 0.0F, -1.4486233F);
      this.hair_27 = new AdvancedModelBox(this, 8, 35);
      this.hair_27.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_27.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_27, 0.61086524F, 0.0F, 0.0F);
      this.jointLB = new AdvancedModelBox(this, 8, 0);
      this.jointLB.setRotationPoint(3.5F, 0.5F, -6.0F);
      this.jointLB.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointR2 = new AdvancedModelBox(this, 48, 25);
      this.hair_jointR2.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointR2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.tail = new AdvancedModelBox(this, 36, 39);
      this.tail.setRotationPoint(0.0F, 0.8F, 3.5F);
      this.tail.addBox(-2.5F, -1.5F, 0.0F, 5, 3, 4, 0.0F);
      this.setRotateAngle(this.tail, -0.2268928F, 0.0F, 0.0F);
      this.hair_28 = new AdvancedModelBox(this, 44, 35);
      this.hair_28.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.hair_28.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_28, -2.3212879F, 1.0821041F, 0.0F);
      this.jointFRL1 = new AdvancedModelBox(this, 12, 6);
      this.jointFRL1.setRotationPoint(0.0F, 3.0F, 0.0F);
      this.jointFRL1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_25 = new AdvancedModelBox(this, 32, 34);
      this.hair_25.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_25.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_25, -0.43633232F, 0.0F, 0.0F);
      this.hair_3 = new AdvancedModelBox(this, 22, 24);
      this.hair_3.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_3.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_3, -0.61086524F, 0.0F, 0.0F);
      this.hair_jointL2 = new AdvancedModelBox(this, 5, 23);
      this.hair_jointL2.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointL2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.leg_8 = new AdvancedModelBox(this, 46, 16);
      this.leg_8.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg_8.addBox(-0.5F, -1.5F, -1.0F, 1, 7, 2, 0.0F);
      this.setRotateAngle(this.leg_8, 0.0F, 0.0F, 1.7976891F);
      this.leg_2 = new AdvancedModelBox(this, 52, 8);
      this.leg_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg_2.addBox(-0.5F, -1.7F, -1.0F, 1, 8, 2, 0.0F);
      this.setRotateAngle(this.leg_2, 0.0F, 0.0F, 1.7976891F);
      this.hair_8 = new AdvancedModelBox(this, 35, 26);
      this.hair_8.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_8.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_8, -0.4886922F, 0.0F, 0.0F);
      this.hair_14 = new AdvancedModelBox(this, 13, 29);
      this.hair_14.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.hair_14.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_14, -2.4609141F, 0.0F, 0.0F);
      this.jointFRLX = new AdvancedModelBox(this, 16, 0);
      this.jointFRLX.setRotationPoint(-1.7F, 3.0F, -9.5F);
      this.jointFRLX.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointLL2 = new AdvancedModelBox(this, 59, 32);
      this.hair_jointLL2.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointLL2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.jointFLLY = new AdvancedModelBox(this, 58, 0);
      this.jointFLLY.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.jointFLLY.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.leg_6 = new AdvancedModelBox(this, 58, 8);
      this.leg_6.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg_6.addBox(-0.5F, 0.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.leg_6, 0.0F, 0.0F, -0.38397244F);
      this.hair_19 = new AdvancedModelBox(this, 48, 31);
      this.hair_19.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_19.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_19, 0.61086524F, 0.0F, 0.0F);
      this.hair_jointLL5 = new AdvancedModelBox(this, 37, 34);
      this.hair_jointLL5.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointLL5.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointR3 = new AdvancedModelBox(this, 40, 26);
      this.hair_jointR3.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointR3.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.head = new AdvancedModelBox(this, 20, 0);
      this.head.setRotationPoint(0.0F, -0.3F, -7.1F);
      this.head.addBox(-4.0F, -4.0F, -4.0F, 8, 8, 8, 0.0F);
      this.setRotateAngle(this.head, (float) (-Math.PI / 18), 0.0F, 0.0F);
      this.hair_7 = new AdvancedModelBox(this, 55, 25);
      this.hair_7.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.hair_7.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_7, -2.7576203F, 0.57595867F, 0.0F);
      this.leg_5 = new AdvancedModelBox(this, 40, 16);
      this.leg_5.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg_5.addBox(-0.5F, -1.7F, -1.0F, 1, 8, 2, 0.0F);
      this.setRotateAngle(this.leg_5, 0.0F, 0.0F, 1.7976891F);
      this.leg = new AdvancedModelBox(this, 24, 2);
      this.leg.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg.addBox(-0.5F, 0.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.leg, 0.0F, 0.0F, -0.43633232F);
      this.hair_jointRTR = new AdvancedModelBox(this, 4, 21);
      this.hair_jointRTR.setRotationPoint(-2.0F, 0.0F, -2.4F);
      this.hair_jointRTR.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.leg_7 = new AdvancedModelBox(this, 0, 10);
      this.leg_7.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leg_7.addBox(-0.5F, -0.5F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.leg_7, 0.0F, 0.0F, -1.4486233F);
      this.hair_1 = new AdvancedModelBox(this, 0, 23);
      this.hair_1.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_1, -0.4886922F, 0.0F, 0.0F);
      this.hair_jointL1 = new AdvancedModelBox(this, 58, 21);
      this.hair_jointL1.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointL1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointR1 = new AdvancedModelBox(this, 18, 25);
      this.hair_jointR1.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointR1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.JD_2 = new AdvancedModelBox(this, 24, 6);
      this.JD_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.JD_2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.JD_2, 0.0F, (float) (-Math.PI / 4), 0.0F);
      this.hair_jointRTL = new AdvancedModelBox(this, 0, 21);
      this.hair_jointRTL.setRotationPoint(2.0F, 0.0F, -2.4F);
      this.hair_jointRTL.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.jointBLLX = new AdvancedModelBox(this, 20, 0);
      this.jointBLLX.setRotationPoint(1.7F, 3.8F, -4.7F);
      this.jointBLLX.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_5 = new AdvancedModelBox(this, 13, 25);
      this.hair_5.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_5.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_5, 0.61086524F, 0.0F, 0.0F);
      this.jointFRL2 = new AdvancedModelBox(this, 20, 6);
      this.jointFRL2.setRotationPoint(0.0F, 2.7F, 0.0F);
      this.jointFRL2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_jointR5 = new AdvancedModelBox(this, 20, 28);
      this.hair_jointR5.setRotationPoint(0.0F, 0.0F, 2.0F);
      this.hair_jointR5.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.hair_34 = new AdvancedModelBox(this, 0, 39);
      this.hair_34.setRotationPoint(0.0F, 0.0F, 0.5F);
      this.hair_34.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 3, 0.0F);
      this.setRotateAngle(this.hair_34, 0.61086524F, 0.0F, 0.0F);
      this.hair_29.addChild(this.hair_jointRR2);
      this.head.addChild(this.hair_jointRTRR);
      this.jointBRLX.addChild(this.JD_3);
      this.hair_jointR6.addChild(this.hair_13);
      this.hair_jointLL5.addChild(this.hair_26);
      this.hair_jointLL3.addChild(this.hair_24);
      this.hair_jointLL1.addChild(this.hair_22);
      this.hair_jointR5.addChild(this.hair_12);
      this.hair_3.addChild(this.hair_jointL4);
      this.tail.addChild(this.tail_1);
      this.jointBRL1.addChild(this.leg_10);
      this.hair_jointRR2.addChild(this.hair_30);
      this.hair_jointRTL.addChild(this.hair);
      this.mainbody.addChild(this.body);
      this.hair_30.addChild(this.hair_jointRR3);
      this.hair_jointRR3.addChild(this.hair_31);
      this.hair_4.addChild(this.hair_jointL5);
      this.JD_3.addChild(this.jointBRLY);
      this.hair_14.addChild(this.hair_jointM1);
      this.hair_jointRR1.addChild(this.hair_29);
      this.hair_5.addChild(this.hair_jointL6);
      this.hair_jointRR4.addChild(this.hair_32);
      this.mainbody.addChild(this.joingRB);
      this.hair_12.addChild(this.hair_jointR6);
      this.hair_jointM6.addChild(this.hair_20);
      this.hair_10.addChild(this.hair_jointR4);
      this.jointFRL1.addChild(this.leg_4);
      this.hair_19.addChild(this.hair_jointM6);
      this.jointFLLX.addChild(this.JD);
      this.hair_jointM1.addChild(this.hair_15);
      this.mainbody.addChild(this.jointFLLX);
      this.JD_2.addChild(this.jointBLLY);
      this.leg_6.addChild(this.jointBLL1);
      this.jointFRLY.addChild(this.leg_3);
      this.hair_18.addChild(this.hair_jointM5);
      this.hair_jointM2.addChild(this.hair_16);
      this.hair_17.addChild(this.hair_jointM4);
      this.mainbody.addChild(this.jointBRLX);
      this.leg_1.addChild(this.jointFLL2);
      this.hair_31.addChild(this.hair_jointRR4);
      this.hair_21.addChild(this.hair_jointLL1);
      this.hair_26.addChild(this.hair_jointLL6);
      this.hair_2.addChild(this.hair_jointL3);
      this.head.addChild(this.hair_jointRTM);
      this.hair_32.addChild(this.hair_jointRR5);
      this.jointBRLY.addChild(this.leg_9);
      this.hair_jointL2.addChild(this.hair_2);
      this.body_1.addChild(this.body_2);
      this.jointFRLX.addChild(this.JD_1);
      this.hair_jointRR5.addChild(this.hair_33);
      this.hair_jointLL2.addChild(this.hair_23);
      this.leg.addChild(this.jointFLL1);
      this.leg_7.addChild(this.jointBLL2);
      this.body_3.addChild(this.body_4);
      this.hair_28.addChild(this.hair_jointRR1);
      this.hair_23.addChild(this.hair_jointLL3);
      this.hair_jointR3.addChild(this.hair_10);
      this.hair_jointR4.addChild(this.hair_11);
      this.jointBRL2.addChild(this.leg_11);
      this.hair_jointL4.addChild(this.hair_4);
      this.head.addChild(this.hair_jointRTLL);
      this.hair_jointR2.addChild(this.hair_9);
      this.hair_jointL6.addChild(this.hair_6);
      this.leg_9.addChild(this.jointBRL1);
      this.jointLB.addChild(this.body_3);
      this.hair_jointM4.addChild(this.hair_18);
      this.hair_24.addChild(this.hair_jointLL4);
      this.joingRB.addChild(this.body_1);
      this.hair_16.addChild(this.hair_jointM3);
      this.hair_jointRTLL.addChild(this.hair_21);
      this.hair_33.addChild(this.hair_jointRR6);
      this.leg_10.addChild(this.jointBRL2);
      this.JD_1.addChild(this.jointFRLY);
      this.hair_15.addChild(this.hair_jointM2);
      this.hair_jointM3.addChild(this.hair_17);
      this.jointFLL1.addChild(this.leg_1);
      this.hair_jointLL6.addChild(this.hair_27);
      this.mainbody.addChild(this.jointLB);
      this.hair_8.addChild(this.hair_jointR2);
      this.body.addChild(this.tail);
      this.hair_jointRTRR.addChild(this.hair_28);
      this.leg_3.addChild(this.jointFRL1);
      this.hair_jointLL4.addChild(this.hair_25);
      this.hair_jointL3.addChild(this.hair_3);
      this.hair_1.addChild(this.hair_jointL2);
      this.jointBLL2.addChild(this.leg_8);
      this.jointFLL2.addChild(this.leg_2);
      this.hair_jointR1.addChild(this.hair_8);
      this.hair_jointRTM.addChild(this.hair_14);
      this.mainbody.addChild(this.jointFRLX);
      this.hair_22.addChild(this.hair_jointLL2);
      this.JD.addChild(this.jointFLLY);
      this.jointBLLY.addChild(this.leg_6);
      this.hair_jointM5.addChild(this.hair_19);
      this.hair_25.addChild(this.hair_jointLL5);
      this.hair_9.addChild(this.hair_jointR3);
      this.mainbody.addChild(this.head);
      this.hair_jointRTR.addChild(this.hair_7);
      this.jointFRL2.addChild(this.leg_5);
      this.jointFLLY.addChild(this.leg);
      this.head.addChild(this.hair_jointRTR);
      this.jointBLL1.addChild(this.leg_7);
      this.hair_jointL1.addChild(this.hair_1);
      this.hair.addChild(this.hair_jointL1);
      this.hair_7.addChild(this.hair_jointR1);
      this.jointBLLX.addChild(this.JD_2);
      this.head.addChild(this.hair_jointRTL);
      this.mainbody.addChild(this.jointBLLX);
      this.hair_jointL5.addChild(this.hair_5);
      this.leg_4.addChild(this.jointFRL2);
      this.hair_11.addChild(this.hair_jointR5);
      this.hair_jointRR6.addChild(this.hair_34);
      this.captureDefaultPose();
   }

   @Override
   protected void func_78087_a(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, RupterEntity entityIn) {
      RupterEntity parasite = entityIn;
      this.jointFLLX.rotateAngleY = 0.0F;
      this.jointFLLY.rotateAngleZ = 0.0F;
      this.jointFRLX.rotateAngleY = 0.0F;
      this.jointFRLY.rotateAngleZ = 0.0F;
      this.jointFLL1.rotateAngleZ = 0.0F;
      this.jointFRL1.rotateAngleZ = 0.0F;
      this.jointBLLX.rotateAngleY = 0.0F;
      this.jointBLLY.rotateAngleZ = 0.0F;
      this.jointBRLX.rotateAngleY = 0.0F;
      this.jointBRLY.rotateAngleZ = 0.0F;
      this.mainbody.offsetY = 0.0F;
      this.mainbody.rotateAngleX = 0.0F;
      this.hair_jointM1.rotateAngleX = 0.0F;
      this.hair_jointM2.rotateAngleX = 0.0F;
      this.hair_jointM3.rotateAngleX = 0.0F;
      this.hair_jointM4.rotateAngleX = 0.0F;
      this.hair_jointM5.rotateAngleX = 0.0F;
      this.hair_jointM6.rotateAngleX = 0.0F;
      this.hair_jointL1.rotateAngleX = 0.0F;
      this.hair_jointL2.rotateAngleX = 0.0F;
      this.hair_jointL3.rotateAngleX = 0.0F;
      this.hair_jointL4.rotateAngleX = 0.0F;
      this.hair_jointL5.rotateAngleX = 0.0F;
      this.hair_jointL6.rotateAngleX = 0.0F;
      this.hair_jointR1.rotateAngleX = 0.0F;
      this.hair_jointR2.rotateAngleX = 0.0F;
      this.hair_jointR3.rotateAngleX = 0.0F;
      this.hair_jointR4.rotateAngleX = 0.0F;
      this.hair_jointR5.rotateAngleX = 0.0F;
      this.hair_jointR6.rotateAngleX = 0.0F;
      this.hair_jointLL1.rotateAngleX = 0.0F;
      this.hair_jointLL2.rotateAngleX = 0.0F;
      this.hair_jointLL3.rotateAngleX = 0.0F;
      this.hair_jointLL4.rotateAngleX = 0.0F;
      this.hair_jointLL5.rotateAngleX = 0.0F;
      this.hair_jointLL6.rotateAngleX = 0.0F;
      this.hair_jointRR1.rotateAngleX = 0.0F;
      this.hair_jointRR2.rotateAngleX = 0.0F;
      this.hair_jointRR3.rotateAngleX = 0.0F;
      this.hair_jointRR4.rotateAngleX = 0.0F;
      this.hair_jointRR5.rotateAngleX = 0.0F;
      this.hair_jointRR6.rotateAngleX = 0.0F;
      int i = parasite.getParasiteStatus();
      if (i == 0) {
         if (!parasite.getStillAni()) {
            float GS = 2.7F;
            float GD = 0.4F;
            this.swingY(this.jointFLLX, 0.2F * GS, 1.5F * GD, -1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointFLLY, 0.2F * GS, 1.0F * GD, 1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.swingY(this.jointFRLX, 0.2F * GS, 1.5F * GD, -1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointFRLY, 0.2F * GS, 1.0F * GD, -1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.swingY(this.jointBLLX, 0.2F * GS, 1.5F * GD, 1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointBLLY, 0.2F * GS, 1.0F * GD, -1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.swingY(this.jointBRLX, 0.2F * GS, 1.5F * GD, 1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointBRLY, 0.2F * GS, 1.0F * GD, 1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.moveY(this.mainbody, 0.4F * GS, 1, limbSwing, limbSwingAmount, 0.02F);
         }

         float f2 = Mth.cos(ageInTicks * 0.1F) * 0.05F;
         float nf2 = -1.0F * f2;
         this.hair_jointM1.rotateAngleX = f2;
         this.hair_jointM2.rotateAngleX = f2;
         this.hair_jointM3.rotateAngleX = f2;
         this.hair_jointM4.rotateAngleX = f2;
         this.hair_jointM5.rotateAngleX = f2;
         this.hair_jointM6.rotateAngleX = f2;
         this.hair_jointL1.rotateAngleX = nf2;
         this.hair_jointL2.rotateAngleX = nf2;
         this.hair_jointL3.rotateAngleX = nf2;
         this.hair_jointL4.rotateAngleX = nf2;
         this.hair_jointL5.rotateAngleX = nf2;
         this.hair_jointL6.rotateAngleX = nf2;
         this.hair_jointR1.rotateAngleX = nf2;
         this.hair_jointR2.rotateAngleX = nf2;
         this.hair_jointR3.rotateAngleX = nf2;
         this.hair_jointR4.rotateAngleX = nf2;
         this.hair_jointR5.rotateAngleX = nf2;
         this.hair_jointR6.rotateAngleX = nf2;
         this.hair_jointLL1.rotateAngleX = f2;
         this.hair_jointLL2.rotateAngleX = f2;
         this.hair_jointLL3.rotateAngleX = f2;
         this.hair_jointLL4.rotateAngleX = f2;
         this.hair_jointLL5.rotateAngleX = f2;
         this.hair_jointLL6.rotateAngleX = f2;
         this.hair_jointRR1.rotateAngleX = f2;
         this.hair_jointRR2.rotateAngleX = f2;
         this.hair_jointRR3.rotateAngleX = f2;
         this.hair_jointRR4.rotateAngleX = f2;
         this.hair_jointRR5.rotateAngleX = f2;
         this.hair_jointRR6.rotateAngleX = f2;
      } else if (i == 1) {
         if (!parasite.getStillAni()) {
            float GS = 2.7F;
            float GD = 0.4F;
            this.swingY(this.jointFLLX, 0.2F * GS, 1.5F * GD, -1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointFLLY, 0.2F * GS, 1.0F * GD, 1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.swingY(this.jointFRLX, 0.2F * GS, 1.5F * GD, -1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointFRLY, 0.2F * GS, 1.0F * GD, -1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.swingY(this.jointBLLX, 0.2F * GS, 1.5F * GD, 1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointBLLY, 0.2F * GS, 1.0F * GD, -1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.swingY(this.jointBRLX, 0.2F * GS, 1.5F * GD, 1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointBRLY, 0.2F * GS, 1.0F * GD, 1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.moveY(this.mainbody, 0.4F * GS, 1, limbSwing, limbSwingAmount, 0.02F);
         }

         float f2 = 0.3F + Mth.cos(ageInTicks * 0.8F) * 0.08F;
         float nf2 = 0.6F + -1.0F * f2;
         this.hair_jointM1.rotateAngleX = f2;
         this.hair_jointM2.rotateAngleX = f2;
         this.hair_jointM3.rotateAngleX = f2;
         this.hair_jointM4.rotateAngleX = f2;
         this.hair_jointM5.rotateAngleX = f2;
         this.hair_jointM6.rotateAngleX = f2;
         this.hair_jointL1.rotateAngleX = nf2;
         this.hair_jointL2.rotateAngleX = nf2;
         this.hair_jointL3.rotateAngleX = nf2;
         this.hair_jointL4.rotateAngleX = nf2;
         this.hair_jointL5.rotateAngleX = nf2;
         this.hair_jointL6.rotateAngleX = nf2;
         this.hair_jointR1.rotateAngleX = nf2;
         this.hair_jointR2.rotateAngleX = nf2;
         this.hair_jointR3.rotateAngleX = nf2;
         this.hair_jointR4.rotateAngleX = nf2;
         this.hair_jointR5.rotateAngleX = nf2;
         this.hair_jointR6.rotateAngleX = nf2;
         this.hair_jointLL1.rotateAngleX = f2;
         this.hair_jointLL2.rotateAngleX = f2;
         this.hair_jointLL3.rotateAngleX = f2;
         this.hair_jointLL4.rotateAngleX = f2;
         this.hair_jointLL5.rotateAngleX = f2;
         this.hair_jointLL6.rotateAngleX = f2;
         this.hair_jointRR1.rotateAngleX = f2;
         this.hair_jointRR2.rotateAngleX = f2;
         this.hair_jointRR3.rotateAngleX = f2;
         this.hair_jointRR4.rotateAngleX = f2;
         this.hair_jointRR5.rotateAngleX = f2;
         this.hair_jointRR6.rotateAngleX = f2;
      } else if (i == 2) {
         if (!parasite.getStillAni()) {
            float GS = 1.2F;
            float GD = 0.5F;
            this.swingY(this.jointFLLX, 0.6F * GS, 1.5F * GD, -1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointFLLY, 0.6F * GS, 1.0F * GD, 1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.swingY(this.jointFRLX, 0.6F * GS, 1.5F * GD, -1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointFRLY, 0.6F * GS, 1.0F * GD, -1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.swingY(this.jointBLLX, 0.6F * GS, 1.5F * GD, 1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointBLLY, 0.6F * GS, 1.0F * GD, -1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.swingY(this.jointBRLX, 0.6F * GS, 1.5F * GD, 1, limbSwing, limbSwingAmount);
            this.swingZ(this.jointBRLY, 0.6F * GS, 1.0F * GD, 1, 1.0F, 0.0F, limbSwing, limbSwingAmount);
            this.moveY(this.mainbody, 1.2F * GS, 1, limbSwing, limbSwingAmount, 0.02F);
         }

         float f2 = 0.3F + Mth.cos(ageInTicks * 0.8F) * 0.08F;
         float nf2 = 0.6F + -1.0F * f2;
         this.hair_jointM1.rotateAngleX = f2;
         this.hair_jointM2.rotateAngleX = f2;
         this.hair_jointM3.rotateAngleX = f2;
         this.hair_jointM4.rotateAngleX = f2;
         this.hair_jointM5.rotateAngleX = f2;
         this.hair_jointM6.rotateAngleX = f2;
         this.hair_jointL1.rotateAngleX = nf2;
         this.hair_jointL2.rotateAngleX = nf2;
         this.hair_jointL3.rotateAngleX = nf2;
         this.hair_jointL4.rotateAngleX = nf2;
         this.hair_jointL5.rotateAngleX = nf2;
         this.hair_jointL6.rotateAngleX = nf2;
         this.hair_jointR1.rotateAngleX = nf2;
         this.hair_jointR2.rotateAngleX = nf2;
         this.hair_jointR3.rotateAngleX = nf2;
         this.hair_jointR4.rotateAngleX = nf2;
         this.hair_jointR5.rotateAngleX = nf2;
         this.hair_jointR6.rotateAngleX = nf2;
         this.hair_jointLL1.rotateAngleX = f2;
         this.hair_jointLL2.rotateAngleX = f2;
         this.hair_jointLL3.rotateAngleX = f2;
         this.hair_jointLL4.rotateAngleX = f2;
         this.hair_jointLL5.rotateAngleX = f2;
         this.hair_jointLL6.rotateAngleX = f2;
         this.hair_jointRR1.rotateAngleX = f2;
         this.hair_jointRR2.rotateAngleX = f2;
         this.hair_jointRR3.rotateAngleX = f2;
         this.hair_jointRR4.rotateAngleX = f2;
         this.hair_jointRR5.rotateAngleX = f2;
         this.hair_jointRR6.rotateAngleX = f2;
      } else if (i == 10) {
         float f2 = Mth.cos(ageInTicks * 0.9F) * 0.04F;
         this.jointFLLY.rotateAngleZ = -0.3F + f2;
         this.jointFRLY.rotateAngleZ = -0.3F + f2;
         this.jointFLL1.rotateAngleZ = -0.1F + f2 * 0.5F;
         this.jointFRL1.rotateAngleZ = -0.1F + f2 * 0.5F;
         this.jointBLLY.rotateAngleZ = f2 * 1.2F;
         this.jointBRLY.rotateAngleZ = f2 * 1.2F;
         this.mainbody.rotateAngleX = -0.9F;
         f2 = 0.3F + Mth.cos(ageInTicks * 0.8F) * 0.08F;
         float nf2 = 0.6F + -1.0F * f2;
         this.hair_jointM1.rotateAngleX = f2;
         this.hair_jointM2.rotateAngleX = f2;
         this.hair_jointM3.rotateAngleX = f2;
         this.hair_jointM4.rotateAngleX = f2;
         this.hair_jointM5.rotateAngleX = f2;
         this.hair_jointM6.rotateAngleX = f2;
         this.hair_jointL1.rotateAngleX = nf2;
         this.hair_jointL2.rotateAngleX = nf2;
         this.hair_jointL3.rotateAngleX = nf2;
         this.hair_jointL4.rotateAngleX = nf2;
         this.hair_jointL5.rotateAngleX = nf2;
         this.hair_jointL6.rotateAngleX = nf2;
         this.hair_jointR1.rotateAngleX = nf2;
         this.hair_jointR2.rotateAngleX = nf2;
         this.hair_jointR3.rotateAngleX = nf2;
         this.hair_jointR4.rotateAngleX = nf2;
         this.hair_jointR5.rotateAngleX = nf2;
         this.hair_jointR6.rotateAngleX = nf2;
         this.hair_jointLL1.rotateAngleX = f2;
         this.hair_jointLL2.rotateAngleX = f2;
         this.hair_jointLL3.rotateAngleX = f2;
         this.hair_jointLL4.rotateAngleX = f2;
         this.hair_jointLL5.rotateAngleX = f2;
         this.hair_jointLL6.rotateAngleX = f2;
         this.hair_jointRR1.rotateAngleX = f2;
         this.hair_jointRR2.rotateAngleX = f2;
         this.hair_jointRR3.rotateAngleX = f2;
         this.hair_jointRR4.rotateAngleX = f2;
         this.hair_jointRR5.rotateAngleX = f2;
         this.hair_jointRR6.rotateAngleX = f2;
      }

      this.underground(parasite, ageInTicks, this.mainbody);
   }
}
