package alku.csrp.client.model.tabula.inborn;

import alku.csrp.client.model.tabula.ModelSRP;
import alku.csrp.entity.BuglinEntity;
import com.github.alexthe666.citadel.client.model.AdvancedModelBox;
import net.minecraft.util.Mth;

/** Direct Citadel port of SRParasites 1.10.8's Tabula-exported {@code ModelLodo}. */
public final class ModelLodo extends ModelSRP<BuglinEntity> {
    public AdvancedModelBox mainbody;
    public AdvancedModelBox bodyfront;
    public AdvancedModelBox joint1;
    public AdvancedModelBox dec;
    public AdvancedModelBox dec_1;
    public AdvancedModelBox dec_2;
    public AdvancedModelBox dec_3;
    public AdvancedModelBox body;
    public AdvancedModelBox joint2;
    public AdvancedModelBox bodyMiddle;
    public AdvancedModelBox joint3;
    public AdvancedModelBox dec_4;
    public AdvancedModelBox dec_5;
    public AdvancedModelBox dec_6;
    public AdvancedModelBox dec_7;
    public AdvancedModelBox dec_8;
    public AdvancedModelBox dec_9;
    public AdvancedModelBox dec_10;
    public AdvancedModelBox body_1;
    public AdvancedModelBox joint4;
    public AdvancedModelBox bodyback;
    public AdvancedModelBox joint5;
    public AdvancedModelBox dec_11;
    public AdvancedModelBox dec_12;
    public AdvancedModelBox dec_13;
    public AdvancedModelBox dec_14;
    public AdvancedModelBox body_2;

    public ModelLodo() {
        this.texWidth = 64;
        this.texHeight = 16;
        this.bodyMiddle = new AdvancedModelBox(this, 16, 3);
        this.bodyMiddle.setRotationPoint(0.0F, 0.0F, 2.5F);
        this.bodyMiddle.addBox(-3.0F, -3.0F, -1.5F, 6, 4, 3, 0.0F);
        this.dec_4 = new AdvancedModelBox(this, 31, 2);
        this.dec_4.setRotationPoint(0.0F, -2.6F, -0.7F);
        this.dec_4.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_4, -0.38397244F, 0.0F, 0.0F);
        this.dec_7 = new AdvancedModelBox(this, 31, 4);
        this.dec_7.setRotationPoint(2.6F, -1.7F, -0.7F);
        this.dec_7.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_7, 0.0F, -0.38397244F, 0.0F);
        this.dec_1 = new AdvancedModelBox(this, 26, 0);
        this.dec_1.setRotationPoint(-0.9F, -0.5F, -0.2F);
        this.dec_1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_1, -0.38397244F, 0.0F, 0.0F);
        this.dec_11 = new AdvancedModelBox(this, 8, 5);
        this.dec_11.setRotationPoint(-0.9F, -0.6F, 1.2F);
        this.dec_11.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_11, -0.38397244F, 0.0F, 0.0F);
        this.body = new AdvancedModelBox(this, 35, 0);
        this.body.setRotationPoint(0.0F, 0.0F, 1.5F);
        this.body.addBox(-2.5F, -2.0F, -1.0F, 5, 3, 3, 0.0F);
        this.dec_10 = new AdvancedModelBox(this, 0, 5);
        this.dec_10.setRotationPoint(-2.6F, -0.2F, -0.7F);
        this.dec_10.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_10, 0.0F, 0.38397244F, 0.0F);
        this.joint4 = new AdvancedModelBox(this, 2, 5);
        this.joint4.setRotationPoint(0.0F, 0.0F, 0.4F);
        this.joint4.addBox(-1.0F, 0.0F, 0.0F, 2, 1, 2, 0.0F);
        this.dec_2 = new AdvancedModelBox(this, 30, 0);
        this.dec_2.setRotationPoint(1.5F, 0.0F, -0.2F);
        this.dec_2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_2, 0.0F, -0.38397244F, 0.0F);
        this.dec_5 = new AdvancedModelBox(this, 0, 3);
        this.dec_5.setRotationPoint(1.8F, -2.6F, -0.7F);
        this.dec_5.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_5, -0.38397244F, 0.0F, 0.0F);
        this.joint3 = new AdvancedModelBox(this, 54, 1);
        this.joint3.setRotationPoint(0.0F, 0.0F, 0.4F);
        this.joint3.addBox(-1.0F, 0.0F, 0.0F, 2, 1, 2, 0.0F);
        this.joint5 = new AdvancedModelBox(this, 47, 6);
        this.joint5.setRotationPoint(0.0F, 0.0F, 0.4F);
        this.joint5.addBox(-1.0F, 0.0F, 0.0F, 2, 1, 2, 0.0F);
        this.dec = new AdvancedModelBox(this, 22, 0);
        this.dec.setRotationPoint(0.9F, -0.5F, -0.2F);
        this.dec.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec, -0.38397244F, 0.0F, 0.0F);
        this.bodyback = new AdvancedModelBox(this, 0, 8);
        this.bodyback.setRotationPoint(0.0F, 0.0F, 1.5F);
        this.bodyback.addBox(-2.0F, -1.0F, -2.0F, 4, 2, 4, 0.0F);
        this.dec_6 = new AdvancedModelBox(this, 51, 3);
        this.dec_6.setRotationPoint(-1.8F, -2.6F, -0.7F);
        this.dec_6.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_6, -0.38397244F, 0.0F, 0.0F);
        this.mainbody = new AdvancedModelBox(this, 0, 0);
        this.mainbody.setRotationPoint(0.0F, 23.0F, -3.0F);
        this.mainbody.addBox(-1.0F, 0.0F, -3.0F, 2, 1, 2, 0.0F);
        this.dec_8 = new AdvancedModelBox(this, 54, 4);
        this.dec_8.setRotationPoint(2.6F, -0.2F, -0.7F);
        this.dec_8.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_8, 0.0F, -0.38397244F, 0.0F);
        this.dec_3 = new AdvancedModelBox(this, 34, 0);
        this.dec_3.setRotationPoint(-1.5F, 0.0F, -0.2F);
        this.dec_3.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_3, 0.0F, 0.38397244F, 0.0F);
        this.dec_14 = new AdvancedModelBox(this, 57, 6);
        this.dec_14.setRotationPoint(-1.6F, 0.0F, 1.2F);
        this.dec_14.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_14, 0.0F, 0.38397244F, 0.0F);
        this.body_2 = new AdvancedModelBox(this, 45, 9);
        this.body_2.setRotationPoint(0.0F, 0.0F, 1.5F);
        this.body_2.addBox(-1.0F, 0.0F, -2.0F, 2, 1, 5, 0.0F);
        this.dec_12 = new AdvancedModelBox(this, 12, 5);
        this.dec_12.setRotationPoint(0.9F, -0.6F, 1.2F);
        this.dec_12.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_12, -0.38397244F, 0.0F, 0.0F);
        this.dec_9 = new AdvancedModelBox(this, 58, 4);
        this.dec_9.setRotationPoint(-2.6F, -1.7F, -0.7F);
        this.dec_9.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_9, 0.0F, 0.38397244F, 0.0F);
        this.dec_13 = new AdvancedModelBox(this, 53, 6);
        this.dec_13.setRotationPoint(1.6F, 0.0F, 1.2F);
        this.dec_13.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
        this.setRotateAngle(this.dec_13, 0.0F, -0.38397244F, 0.0F);
        this.bodyfront = new AdvancedModelBox(this, 5, 0);
        this.bodyfront.setRotationPoint(0.0F, 0.0F, -1.5F);
        this.bodyfront.addBox(-2.0F, -1.0F, -1.0F, 4, 2, 3, 0.0F);
        this.joint2 = new AdvancedModelBox(this, 48, 0);
        this.joint2.setRotationPoint(0.0F, 0.0F, -0.5F);
        this.joint2.addBox(-1.0F, 0.0F, 0.0F, 2, 1, 2, 0.0F);
        this.body_1 = new AdvancedModelBox(this, 34, 6);
        this.body_1.setRotationPoint(0.0F, 0.0F, 1.5F);
        this.body_1.addBox(-2.5F, -2.0F, -2.0F, 5, 3, 3, 0.0F);
        this.joint1 = new AdvancedModelBox(this, 16, 0);
        this.joint1.setRotationPoint(0.0F, 0.0F, 0.4F);
        this.joint1.addBox(-1.0F, 0.0F, 0.0F, 2, 1, 2, 0.0F);
        this.joint2.addChild(this.bodyMiddle);
        this.bodyMiddle.addChild(this.dec_4);
        this.bodyMiddle.addChild(this.dec_7);
        this.bodyfront.addChild(this.dec_1);
        this.bodyback.addChild(this.dec_11);
        this.joint1.addChild(this.body);
        this.bodyMiddle.addChild(this.dec_10);
        this.body_1.addChild(this.joint4);
        this.bodyfront.addChild(this.dec_2);
        this.bodyMiddle.addChild(this.dec_5);
        this.bodyMiddle.addChild(this.joint3);
        this.bodyback.addChild(this.joint5);
        this.bodyfront.addChild(this.dec);
        this.joint4.addChild(this.bodyback);
        this.bodyMiddle.addChild(this.dec_6);
        this.bodyMiddle.addChild(this.dec_8);
        this.bodyfront.addChild(this.dec_3);
        this.bodyback.addChild(this.dec_14);
        this.joint5.addChild(this.body_2);
        this.bodyback.addChild(this.dec_12);
        this.bodyMiddle.addChild(this.dec_9);
        this.bodyback.addChild(this.dec_13);
        this.mainbody.addChild(this.bodyfront);
        this.body.addChild(this.joint2);
        this.joint3.addChild(this.body_1);
        this.bodyfront.addChild(this.joint1);
        this.captureDefaultPose();
    }

    @Override
    protected void func_78087_a(float limbSwing, float limbSwingAmount, float ageInTicks,
                                 float netHeadYaw, float headPitch, float scaleFactor,
                                 BuglinEntity entityIn) {
        float floorTimer = entityIn.getTabulaFloorTimer();
        if (floorTimer >= 0.0F) {
            float offsetX = Mth.cos(ageInTicks * 2.6F) * 0.015F;
            float offsetZ = Mth.cos(ageInTicks * 2.27F) * 0.02F;
            this.mainbody.offsetX = offsetX;
            this.mainbody.offsetZ = 0.2F;
            this.mainbody.rotateAngleX = 1.6F;
            this.mainbody.offsetY = floorTimer;
            float jointYaw = Mth.cos(ageInTicks * 0.643219F) * 0.06510051F;
            float bodyRoll = Mth.cos(ageInTicks * 0.643219F) * 0.06510015F;
            this.joint1.rotateAngleY = jointYaw;
            this.joint2.rotateAngleY = jointYaw;
            this.joint3.rotateAngleY = jointYaw;
            this.joint4.rotateAngleY = jointYaw;
            this.joint5.rotateAngleY = jointYaw;
            this.mainbody.rotateAngleZ = bodyRoll;
            this.bodyMiddle.rotateAngleZ = bodyRoll;
        } else {
            float jointYaw = Mth.cos(limbSwing * 1.5F) * limbSwingAmount * 0.25F;
            float bodyRoll = Mth.cos(limbSwing * 1.5F) * limbSwingAmount * 0.15F;
            this.joint1.rotateAngleY = jointYaw;
            this.joint2.rotateAngleY = jointYaw;
            this.joint3.rotateAngleY = jointYaw;
            this.joint4.rotateAngleY = jointYaw;
            this.joint5.rotateAngleY = jointYaw;
            this.mainbody.rotateAngleZ = bodyRoll;
            this.bodyMiddle.rotateAngleZ = bodyRoll;
        }
    }
}
