org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.235
neo_version_range=[21,)
loader_version_range=[4,)
mod_id=nocubessrparmory
mod_name=SRP Combat Addon: Armory
mod_license=MIT
mod_version=3.0.0-port.1
mod_group_id=alku.nocubessrparmory
mod_authors=NoCube, port by csrp team
mod_description=Balanced weapons and armor for Scape and Run: Parasites; 1.21.1 NeoForge port.
